import { mixed } from "./example/mixed";
import { variable } from "./example/variable";
import { exampleTypeOf } from "./example/exampleTypeOf";
import { exampleLenght } from "./example/exampleLenght";
import { exampleEval } from "./example/exampleEval";
import { exampleTrim } from "./example/exampleTrim";
import { exampleSlice } from "./example/exampleSlice";
import { exampleSubString } from "./example/exampleSubString";
import { exampleSubStr } from "./example/exampleSubStr";
import { exampleConcat } from "./example/exampleConcat";
import { exampleRepeat } from "./example/exampleRepeat";
import { exampleToString } from "./example/exampleTostring";
import { exampleString } from "./example/exampleString";
import { exampleNumber } from "./example/exampleNumber";
import { exampleValueOf } from "./example/exampleValueOf";
import { exampleIndexOf } from "./example/exampleIndexOf";
import { exampleLastIndexOf } from "./example/exampleLastIndexOf";
import { exampleSearch } from "./example/exampleSearch";
import { exampleIncludes } from "./example/exampleIncludes";
import { exampleStartsWith } from "./example/exampleStartsWith";
import { exampleEndsWith } from "./example/exampleEndsWith";
import { exampleMatch } from "./example/exampleMatch";
import { exampleReplace } from "./example/exampleReplace";
import { exampleSplit } from "./example/exampleSplit";
import { exampleLocaleCompare } from "./example/exampleLocaleCompare";
import { exampleCharAt } from "./example/exampleCharAt";
import { exampleCharCodeAt } from "./example/exampleCharCodeAt";
import { exampleFromCharCode } from "./example/exampleFromCharCode";
import { exampleEncodeUri } from "./example/exampleEncodeUri";
import { exampleDecodeUri } from "./example/exampleDecodeUri";
import { exampleEncodeUriComponent } from "./example/exampleEncodeUriComponent";
import { exampleEscape } from "./example/exampleEscape";
import { exampleUnEscape } from "./example/exampleUnEscape";
import { exampleToUpperCase } from "./example/exampleToUpperCase";
import { exampleToLowerCase } from "./example/exampleToLowerCase";
import { exampleToLocaleUpperCase } from "./example/exampleToLocaleUpperCase";
import { exampleToLocaleLowerCase } from "./example/exampleToLocaleLowerCase";
import { exampleSub } from "./example/exampleSub";
import { exampleSup } from "./example/exampleSup";
import { exampleBig } from "./example/exampleBig";
import { exampleSmall } from "./example/exampleSmall";
import { exampleBold } from "./example/exampleBold";

//Welcome Text
document.querySelector("#app").innerHTML =
  '<h1 style="text-align: center;">Hello JavaScript</h1>';

mixed();
variable();
exampleTypeOf();
exampleLenght();
exampleEval();
exampleTrim();
exampleSlice();
exampleSubString();
exampleSubStr();
exampleConcat();
exampleRepeat();
exampleToString();
exampleString();
exampleNumber();
exampleValueOf();
exampleIndexOf();
exampleLastIndexOf();
exampleSearch();
exampleIncludes();
exampleStartsWith();
exampleEndsWith();
exampleMatch();
exampleReplace();
exampleSplit();
exampleLocaleCompare();
exampleCharAt();
exampleCharCodeAt();
exampleFromCharCode();
exampleEncodeUri();
exampleDecodeUri();
exampleEncodeUriComponent();
exampleEscape();
exampleUnEscape();
exampleToUpperCase();
exampleToLowerCase();
exampleToLocaleUpperCase();
exampleToLocaleLowerCase();
exampleSub();
exampleSup();
exampleBig();
exampleSmall();
exampleBold();
